package com.ionvaranita.belotenote.alarmee

import com.tweener.alarmee.configuration.AlarmeeIosPlatformConfiguration
import com.tweener.alarmee.configuration.AlarmeePlatformConfiguration

val platformConfiguration: AlarmeePlatformConfiguration = AlarmeeIosPlatformConfiguration